// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: minecraft.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinecraftService_GetVitalSigns_FullMethodName         = "/minecraft.MinecraftService/GetVitalSigns"
	MinecraftService_GetSurroundings_FullMethodName       = "/minecraft.MinecraftService/GetSurroundings"
	MinecraftService_GetInventory_FullMethodName          = "/minecraft.MinecraftService/GetInventory"
	MinecraftService_TakeScreenshot_FullMethodName        = "/minecraft.MinecraftService/TakeScreenshot"
	MinecraftService_MoveTo_FullMethodName                = "/minecraft.MinecraftService/MoveTo"
	MinecraftService_LookAt_FullMethodName                = "/minecraft.MinecraftService/LookAt"
	MinecraftService_PlaceBlock_FullMethodName            = "/minecraft.MinecraftService/PlaceBlock"
	MinecraftService_DigBlock_FullMethodName              = "/minecraft.MinecraftService/DigBlock"
	MinecraftService_EquipItem_FullMethodName             = "/minecraft.MinecraftService/EquipItem"
	MinecraftService_UseItem_FullMethodName               = "/minecraft.MinecraftService/UseItem"
	MinecraftService_AttackEntity_FullMethodName          = "/minecraft.MinecraftService/AttackEntity"
	MinecraftService_Jump_FullMethodName                  = "/minecraft.MinecraftService/Jump"
	MinecraftService_SetSneak_FullMethodName              = "/minecraft.MinecraftService/SetSneak"
	MinecraftService_SendChat_FullMethodName              = "/minecraft.MinecraftService/SendChat"
	MinecraftService_NavigateTo_FullMethodName            = "/minecraft.MinecraftService/NavigateTo"
	MinecraftService_InteractWithEntity_FullMethodName    = "/minecraft.MinecraftService/InteractWithEntity"
	MinecraftService_OpenContainer_FullMethodName         = "/minecraft.MinecraftService/OpenContainer"
	MinecraftService_WithdrawFromContainer_FullMethodName = "/minecraft.MinecraftService/WithdrawFromContainer"
	MinecraftService_DepositToContainer_FullMethodName    = "/minecraft.MinecraftService/DepositToContainer"
	MinecraftService_CraftItem_FullMethodName             = "/minecraft.MinecraftService/CraftItem"
	MinecraftService_SmeltItem_FullMethodName             = "/minecraft.MinecraftService/SmeltItem"
	MinecraftService_Eat_FullMethodName                   = "/minecraft.MinecraftService/Eat"
	MinecraftService_HarvestBlock_FullMethodName          = "/minecraft.MinecraftService/HarvestBlock"
	MinecraftService_Gather_FullMethodName                = "/minecraft.MinecraftService/Gather"
	MinecraftService_BuildStructure_FullMethodName        = "/minecraft.MinecraftService/BuildStructure"
	MinecraftService_ProcessAll_FullMethodName            = "/minecraft.MinecraftService/ProcessAll"
	MinecraftService_OrganizeInventory_FullMethodName     = "/minecraft.MinecraftService/OrganizeInventory"
	MinecraftService_ClearArea_FullMethodName             = "/minecraft.MinecraftService/ClearArea"
	MinecraftService_Farm_FullMethodName                  = "/minecraft.MinecraftService/Farm"
	MinecraftService_SurveyArea_FullMethodName            = "/minecraft.MinecraftService/SurveyArea"
	MinecraftService_FindNearest_FullMethodName           = "/minecraft.MinecraftService/FindNearest"
	MinecraftService_WhatCanICraft_FullMethodName         = "/minecraft.MinecraftService/WhatCanICraft"
	MinecraftService_AssessThreat_FullMethodName          = "/minecraft.MinecraftService/AssessThreat"
	MinecraftService_PlanPath_FullMethodName              = "/minecraft.MinecraftService/PlanPath"
	MinecraftService_SubscribeEvents_FullMethodName       = "/minecraft.MinecraftService/SubscribeEvents"
)

// MinecraftServiceClient is the client API for MinecraftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MinecraftService is the gRPC contract between the Go agent and the
// Node.js Mineflayer sidecar. The sidecar implements this service; the
// Go agent is the client.
type MinecraftServiceClient interface {
	GetVitalSigns(ctx context.Context, in *GetVitalSignsRequest, opts ...grpc.CallOption) (*GetVitalSignsResponse, error)
	GetSurroundings(ctx context.Context, in *GetSurroundingsRequest, opts ...grpc.CallOption) (*GetSurroundingsResponse, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	TakeScreenshot(ctx context.Context, in *TakeScreenshotRequest, opts ...grpc.CallOption) (*TakeScreenshotResponse, error)
	MoveTo(ctx context.Context, in *MoveToRequest, opts ...grpc.CallOption) (*MoveToResponse, error)
	LookAt(ctx context.Context, in *LookAtRequest, opts ...grpc.CallOption) (*LookAtResponse, error)
	PlaceBlock(ctx context.Context, in *PlaceBlockRequest, opts ...grpc.CallOption) (*PlaceBlockResponse, error)
	DigBlock(ctx context.Context, in *DigBlockRequest, opts ...grpc.CallOption) (*DigBlockResponse, error)
	EquipItem(ctx context.Context, in *EquipItemRequest, opts ...grpc.CallOption) (*EquipItemResponse, error)
	UseItem(ctx context.Context, in *UseItemRequest, opts ...grpc.CallOption) (*UseItemResponse, error)
	AttackEntity(ctx context.Context, in *AttackEntityRequest, opts ...grpc.CallOption) (*AttackEntityResponse, error)
	Jump(ctx context.Context, in *JumpRequest, opts ...grpc.CallOption) (*JumpResponse, error)
	SetSneak(ctx context.Context, in *SetSneakRequest, opts ...grpc.CallOption) (*SetSneakResponse, error)
	SendChat(ctx context.Context, in *SendChatRequest, opts ...grpc.CallOption) (*SendChatResponse, error)
	NavigateTo(ctx context.Context, in *NavigateToRequest, opts ...grpc.CallOption) (*NavigateToResponse, error)
	InteractWithEntity(ctx context.Context, in *InteractWithEntityRequest, opts ...grpc.CallOption) (*InteractWithEntityResponse, error)
	OpenContainer(ctx context.Context, in *OpenContainerRequest, opts ...grpc.CallOption) (*OpenContainerResponse, error)
	WithdrawFromContainer(ctx context.Context, in *WithdrawFromContainerRequest, opts ...grpc.CallOption) (*WithdrawFromContainerResponse, error)
	DepositToContainer(ctx context.Context, in *DepositToContainerRequest, opts ...grpc.CallOption) (*DepositToContainerResponse, error)
	CraftItem(ctx context.Context, in *CraftItemRequest, opts ...grpc.CallOption) (*CraftItemResponse, error)
	SmeltItem(ctx context.Context, in *SmeltItemRequest, opts ...grpc.CallOption) (*SmeltItemResponse, error)
	Eat(ctx context.Context, in *EatRequest, opts ...grpc.CallOption) (*EatResponse, error)
	HarvestBlock(ctx context.Context, in *HarvestBlockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	Gather(ctx context.Context, in *GatherRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	BuildStructure(ctx context.Context, in *BuildStructureRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	ProcessAll(ctx context.Context, in *ProcessAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	OrganizeInventory(ctx context.Context, in *OrganizeInventoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	ClearArea(ctx context.Context, in *ClearAreaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	Farm(ctx context.Context, in *FarmRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
	SurveyArea(ctx context.Context, in *SurveyAreaRequest, opts ...grpc.CallOption) (*SurveyAreaResponse, error)
	FindNearest(ctx context.Context, in *FindNearestRequest, opts ...grpc.CallOption) (*FindNearestResponse, error)
	WhatCanICraft(ctx context.Context, in *WhatCanICraftRequest, opts ...grpc.CallOption) (*WhatCanICraftResponse, error)
	AssessThreat(ctx context.Context, in *AssessThreatRequest, opts ...grpc.CallOption) (*AssessThreatResponse, error)
	PlanPath(ctx context.Context, in *PlanPathRequest, opts ...grpc.CallOption) (*PlanPathResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error)
}

type minecraftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMinecraftServiceClient(cc grpc.ClientConnInterface) MinecraftServiceClient {
	return &minecraftServiceClient{cc}
}

func (c *minecraftServiceClient) GetVitalSigns(ctx context.Context, in *GetVitalSignsRequest, opts ...grpc.CallOption) (*GetVitalSignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVitalSignsResponse)
	err := c.cc.Invoke(ctx, MinecraftService_GetVitalSigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) GetSurroundings(ctx context.Context, in *GetSurroundingsRequest, opts ...grpc.CallOption) (*GetSurroundingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSurroundingsResponse)
	err := c.cc.Invoke(ctx, MinecraftService_GetSurroundings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, MinecraftService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) TakeScreenshot(ctx context.Context, in *TakeScreenshotRequest, opts ...grpc.CallOption) (*TakeScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeScreenshotResponse)
	err := c.cc.Invoke(ctx, MinecraftService_TakeScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) MoveTo(ctx context.Context, in *MoveToRequest, opts ...grpc.CallOption) (*MoveToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveToResponse)
	err := c.cc.Invoke(ctx, MinecraftService_MoveTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) LookAt(ctx context.Context, in *LookAtRequest, opts ...grpc.CallOption) (*LookAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookAtResponse)
	err := c.cc.Invoke(ctx, MinecraftService_LookAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) PlaceBlock(ctx context.Context, in *PlaceBlockRequest, opts ...grpc.CallOption) (*PlaceBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceBlockResponse)
	err := c.cc.Invoke(ctx, MinecraftService_PlaceBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) DigBlock(ctx context.Context, in *DigBlockRequest, opts ...grpc.CallOption) (*DigBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DigBlockResponse)
	err := c.cc.Invoke(ctx, MinecraftService_DigBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) EquipItem(ctx context.Context, in *EquipItemRequest, opts ...grpc.CallOption) (*EquipItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EquipItemResponse)
	err := c.cc.Invoke(ctx, MinecraftService_EquipItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) UseItem(ctx context.Context, in *UseItemRequest, opts ...grpc.CallOption) (*UseItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseItemResponse)
	err := c.cc.Invoke(ctx, MinecraftService_UseItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) AttackEntity(ctx context.Context, in *AttackEntityRequest, opts ...grpc.CallOption) (*AttackEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttackEntityResponse)
	err := c.cc.Invoke(ctx, MinecraftService_AttackEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) Jump(ctx context.Context, in *JumpRequest, opts ...grpc.CallOption) (*JumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JumpResponse)
	err := c.cc.Invoke(ctx, MinecraftService_Jump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) SetSneak(ctx context.Context, in *SetSneakRequest, opts ...grpc.CallOption) (*SetSneakResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSneakResponse)
	err := c.cc.Invoke(ctx, MinecraftService_SetSneak_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) SendChat(ctx context.Context, in *SendChatRequest, opts ...grpc.CallOption) (*SendChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatResponse)
	err := c.cc.Invoke(ctx, MinecraftService_SendChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) NavigateTo(ctx context.Context, in *NavigateToRequest, opts ...grpc.CallOption) (*NavigateToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateToResponse)
	err := c.cc.Invoke(ctx, MinecraftService_NavigateTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) InteractWithEntity(ctx context.Context, in *InteractWithEntityRequest, opts ...grpc.CallOption) (*InteractWithEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractWithEntityResponse)
	err := c.cc.Invoke(ctx, MinecraftService_InteractWithEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) OpenContainer(ctx context.Context, in *OpenContainerRequest, opts ...grpc.CallOption) (*OpenContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenContainerResponse)
	err := c.cc.Invoke(ctx, MinecraftService_OpenContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) WithdrawFromContainer(ctx context.Context, in *WithdrawFromContainerRequest, opts ...grpc.CallOption) (*WithdrawFromContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawFromContainerResponse)
	err := c.cc.Invoke(ctx, MinecraftService_WithdrawFromContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) DepositToContainer(ctx context.Context, in *DepositToContainerRequest, opts ...grpc.CallOption) (*DepositToContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositToContainerResponse)
	err := c.cc.Invoke(ctx, MinecraftService_DepositToContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) CraftItem(ctx context.Context, in *CraftItemRequest, opts ...grpc.CallOption) (*CraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CraftItemResponse)
	err := c.cc.Invoke(ctx, MinecraftService_CraftItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) SmeltItem(ctx context.Context, in *SmeltItemRequest, opts ...grpc.CallOption) (*SmeltItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmeltItemResponse)
	err := c.cc.Invoke(ctx, MinecraftService_SmeltItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) Eat(ctx context.Context, in *EatRequest, opts ...grpc.CallOption) (*EatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EatResponse)
	err := c.cc.Invoke(ctx, MinecraftService_Eat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) HarvestBlock(ctx context.Context, in *HarvestBlockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[0], MinecraftService_HarvestBlock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HarvestBlockRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_HarvestBlockClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) Gather(ctx context.Context, in *GatherRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[1], MinecraftService_Gather_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatherRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_GatherClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) BuildStructure(ctx context.Context, in *BuildStructureRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[2], MinecraftService_BuildStructure_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildStructureRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_BuildStructureClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) ProcessAll(ctx context.Context, in *ProcessAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[3], MinecraftService_ProcessAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessAllRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_ProcessAllClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) OrganizeInventory(ctx context.Context, in *OrganizeInventoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[4], MinecraftService_OrganizeInventory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrganizeInventoryRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_OrganizeInventoryClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) ClearArea(ctx context.Context, in *ClearAreaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[5], MinecraftService_ClearArea_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClearAreaRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_ClearAreaClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) Farm(ctx context.Context, in *FarmRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[6], MinecraftService_Farm_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FarmRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_FarmClient = grpc.ServerStreamingClient[TaskProgress]

func (c *minecraftServiceClient) SurveyArea(ctx context.Context, in *SurveyAreaRequest, opts ...grpc.CallOption) (*SurveyAreaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyAreaResponse)
	err := c.cc.Invoke(ctx, MinecraftService_SurveyArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) FindNearest(ctx context.Context, in *FindNearestRequest, opts ...grpc.CallOption) (*FindNearestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindNearestResponse)
	err := c.cc.Invoke(ctx, MinecraftService_FindNearest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) WhatCanICraft(ctx context.Context, in *WhatCanICraftRequest, opts ...grpc.CallOption) (*WhatCanICraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhatCanICraftResponse)
	err := c.cc.Invoke(ctx, MinecraftService_WhatCanICraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) AssessThreat(ctx context.Context, in *AssessThreatRequest, opts ...grpc.CallOption) (*AssessThreatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessThreatResponse)
	err := c.cc.Invoke(ctx, MinecraftService_AssessThreat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) PlanPath(ctx context.Context, in *PlanPathRequest, opts ...grpc.CallOption) (*PlanPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanPathResponse)
	err := c.cc.Invoke(ctx, MinecraftService_PlanPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minecraftServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinecraftService_ServiceDesc.Streams[7], MinecraftService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, GameEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_SubscribeEventsClient = grpc.ServerStreamingClient[GameEvent]

// MinecraftServiceServer is the server API for MinecraftService service.
// All implementations must embed UnimplementedMinecraftServiceServer
// for forward compatibility.
//
// MinecraftService is the gRPC contract between the Go agent and the
// Node.js Mineflayer sidecar. The sidecar implements this service; the
// Go agent is the client.
type MinecraftServiceServer interface {
	GetVitalSigns(context.Context, *GetVitalSignsRequest) (*GetVitalSignsResponse, error)
	GetSurroundings(context.Context, *GetSurroundingsRequest) (*GetSurroundingsResponse, error)
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	TakeScreenshot(context.Context, *TakeScreenshotRequest) (*TakeScreenshotResponse, error)
	MoveTo(context.Context, *MoveToRequest) (*MoveToResponse, error)
	LookAt(context.Context, *LookAtRequest) (*LookAtResponse, error)
	PlaceBlock(context.Context, *PlaceBlockRequest) (*PlaceBlockResponse, error)
	DigBlock(context.Context, *DigBlockRequest) (*DigBlockResponse, error)
	EquipItem(context.Context, *EquipItemRequest) (*EquipItemResponse, error)
	UseItem(context.Context, *UseItemRequest) (*UseItemResponse, error)
	AttackEntity(context.Context, *AttackEntityRequest) (*AttackEntityResponse, error)
	Jump(context.Context, *JumpRequest) (*JumpResponse, error)
	SetSneak(context.Context, *SetSneakRequest) (*SetSneakResponse, error)
	SendChat(context.Context, *SendChatRequest) (*SendChatResponse, error)
	NavigateTo(context.Context, *NavigateToRequest) (*NavigateToResponse, error)
	InteractWithEntity(context.Context, *InteractWithEntityRequest) (*InteractWithEntityResponse, error)
	OpenContainer(context.Context, *OpenContainerRequest) (*OpenContainerResponse, error)
	WithdrawFromContainer(context.Context, *WithdrawFromContainerRequest) (*WithdrawFromContainerResponse, error)
	DepositToContainer(context.Context, *DepositToContainerRequest) (*DepositToContainerResponse, error)
	CraftItem(context.Context, *CraftItemRequest) (*CraftItemResponse, error)
	SmeltItem(context.Context, *SmeltItemRequest) (*SmeltItemResponse, error)
	Eat(context.Context, *EatRequest) (*EatResponse, error)
	HarvestBlock(*HarvestBlockRequest, grpc.ServerStreamingServer[TaskProgress]) error
	Gather(*GatherRequest, grpc.ServerStreamingServer[TaskProgress]) error
	BuildStructure(*BuildStructureRequest, grpc.ServerStreamingServer[TaskProgress]) error
	ProcessAll(*ProcessAllRequest, grpc.ServerStreamingServer[TaskProgress]) error
	OrganizeInventory(*OrganizeInventoryRequest, grpc.ServerStreamingServer[TaskProgress]) error
	ClearArea(*ClearAreaRequest, grpc.ServerStreamingServer[TaskProgress]) error
	Farm(*FarmRequest, grpc.ServerStreamingServer[TaskProgress]) error
	SurveyArea(context.Context, *SurveyAreaRequest) (*SurveyAreaResponse, error)
	FindNearest(context.Context, *FindNearestRequest) (*FindNearestResponse, error)
	WhatCanICraft(context.Context, *WhatCanICraftRequest) (*WhatCanICraftResponse, error)
	AssessThreat(context.Context, *AssessThreatRequest) (*AssessThreatResponse, error)
	PlanPath(context.Context, *PlanPathRequest) (*PlanPathResponse, error)
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[GameEvent]) error
	mustEmbedUnimplementedMinecraftServiceServer()
}

// UnimplementedMinecraftServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinecraftServiceServer struct{}

func (UnimplementedMinecraftServiceServer) GetVitalSigns(context.Context, *GetVitalSignsRequest) (*GetVitalSignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVitalSigns not implemented")
}
func (UnimplementedMinecraftServiceServer) GetSurroundings(context.Context, *GetSurroundingsRequest) (*GetSurroundingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSurroundings not implemented")
}
func (UnimplementedMinecraftServiceServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedMinecraftServiceServer) TakeScreenshot(context.Context, *TakeScreenshotRequest) (*TakeScreenshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeScreenshot not implemented")
}
func (UnimplementedMinecraftServiceServer) MoveTo(context.Context, *MoveToRequest) (*MoveToResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveTo not implemented")
}
func (UnimplementedMinecraftServiceServer) LookAt(context.Context, *LookAtRequest) (*LookAtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookAt not implemented")
}
func (UnimplementedMinecraftServiceServer) PlaceBlock(context.Context, *PlaceBlockRequest) (*PlaceBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBlock not implemented")
}
func (UnimplementedMinecraftServiceServer) DigBlock(context.Context, *DigBlockRequest) (*DigBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DigBlock not implemented")
}
func (UnimplementedMinecraftServiceServer) EquipItem(context.Context, *EquipItemRequest) (*EquipItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EquipItem not implemented")
}
func (UnimplementedMinecraftServiceServer) UseItem(context.Context, *UseItemRequest) (*UseItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseItem not implemented")
}
func (UnimplementedMinecraftServiceServer) AttackEntity(context.Context, *AttackEntityRequest) (*AttackEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttackEntity not implemented")
}
func (UnimplementedMinecraftServiceServer) Jump(context.Context, *JumpRequest) (*JumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Jump not implemented")
}
func (UnimplementedMinecraftServiceServer) SetSneak(context.Context, *SetSneakRequest) (*SetSneakResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSneak not implemented")
}
func (UnimplementedMinecraftServiceServer) SendChat(context.Context, *SendChatRequest) (*SendChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChat not implemented")
}
func (UnimplementedMinecraftServiceServer) NavigateTo(context.Context, *NavigateToRequest) (*NavigateToResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NavigateTo not implemented")
}
func (UnimplementedMinecraftServiceServer) InteractWithEntity(context.Context, *InteractWithEntityRequest) (*InteractWithEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InteractWithEntity not implemented")
}
func (UnimplementedMinecraftServiceServer) OpenContainer(context.Context, *OpenContainerRequest) (*OpenContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenContainer not implemented")
}
func (UnimplementedMinecraftServiceServer) WithdrawFromContainer(context.Context, *WithdrawFromContainerRequest) (*WithdrawFromContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawFromContainer not implemented")
}
func (UnimplementedMinecraftServiceServer) DepositToContainer(context.Context, *DepositToContainerRequest) (*DepositToContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositToContainer not implemented")
}
func (UnimplementedMinecraftServiceServer) CraftItem(context.Context, *CraftItemRequest) (*CraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CraftItem not implemented")
}
func (UnimplementedMinecraftServiceServer) SmeltItem(context.Context, *SmeltItemRequest) (*SmeltItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SmeltItem not implemented")
}
func (UnimplementedMinecraftServiceServer) Eat(context.Context, *EatRequest) (*EatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Eat not implemented")
}
func (UnimplementedMinecraftServiceServer) HarvestBlock(*HarvestBlockRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method HarvestBlock not implemented")
}
func (UnimplementedMinecraftServiceServer) Gather(*GatherRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method Gather not implemented")
}
func (UnimplementedMinecraftServiceServer) BuildStructure(*BuildStructureRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method BuildStructure not implemented")
}
func (UnimplementedMinecraftServiceServer) ProcessAll(*ProcessAllRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessAll not implemented")
}
func (UnimplementedMinecraftServiceServer) OrganizeInventory(*OrganizeInventoryRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method OrganizeInventory not implemented")
}
func (UnimplementedMinecraftServiceServer) ClearArea(*ClearAreaRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method ClearArea not implemented")
}
func (UnimplementedMinecraftServiceServer) Farm(*FarmRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Errorf(codes.Unimplemented, "method Farm not implemented")
}
func (UnimplementedMinecraftServiceServer) SurveyArea(context.Context, *SurveyAreaRequest) (*SurveyAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SurveyArea not implemented")
}
func (UnimplementedMinecraftServiceServer) FindNearest(context.Context, *FindNearestRequest) (*FindNearestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNearest not implemented")
}
func (UnimplementedMinecraftServiceServer) WhatCanICraft(context.Context, *WhatCanICraftRequest) (*WhatCanICraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhatCanICraft not implemented")
}
func (UnimplementedMinecraftServiceServer) AssessThreat(context.Context, *AssessThreatRequest) (*AssessThreatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessThreat not implemented")
}
func (UnimplementedMinecraftServiceServer) PlanPath(context.Context, *PlanPathRequest) (*PlanPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanPath not implemented")
}
func (UnimplementedMinecraftServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[GameEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedMinecraftServiceServer) mustEmbedUnimplementedMinecraftServiceServer() {}
func (UnimplementedMinecraftServiceServer) testEmbeddedByValue()                          {}

// UnsafeMinecraftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinecraftServiceServer will
// result in compilation errors.
type UnsafeMinecraftServiceServer interface {
	mustEmbedUnimplementedMinecraftServiceServer()
}

func RegisterMinecraftServiceServer(s grpc.ServiceRegistrar, srv MinecraftServiceServer) {
	// If the following call pancis, it indicates UnimplementedMinecraftServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinecraftService_ServiceDesc, srv)
}

func _MinecraftService_GetVitalSigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVitalSignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).GetVitalSigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_GetVitalSigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).GetVitalSigns(ctx, req.(*GetVitalSignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_GetSurroundings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurroundingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).GetSurroundings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_GetSurroundings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).GetSurroundings(ctx, req.(*GetSurroundingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_TakeScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).TakeScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_TakeScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).TakeScreenshot(ctx, req.(*TakeScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_MoveTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).MoveTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_MoveTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).MoveTo(ctx, req.(*MoveToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_LookAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).LookAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_LookAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).LookAt(ctx, req.(*LookAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_PlaceBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).PlaceBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_PlaceBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).PlaceBlock(ctx, req.(*PlaceBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_DigBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).DigBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_DigBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).DigBlock(ctx, req.(*DigBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_EquipItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).EquipItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_EquipItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).EquipItem(ctx, req.(*EquipItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_UseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).UseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_UseItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).UseItem(ctx, req.(*UseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_AttackEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttackEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).AttackEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_AttackEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).AttackEntity(ctx, req.(*AttackEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_Jump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).Jump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_Jump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).Jump(ctx, req.(*JumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_SetSneak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSneakRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).SetSneak(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_SetSneak_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).SetSneak(ctx, req.(*SetSneakRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_SendChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).SendChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_SendChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).SendChat(ctx, req.(*SendChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_NavigateTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).NavigateTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_NavigateTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).NavigateTo(ctx, req.(*NavigateToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_InteractWithEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractWithEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).InteractWithEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_InteractWithEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).InteractWithEntity(ctx, req.(*InteractWithEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_OpenContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).OpenContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_OpenContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).OpenContainer(ctx, req.(*OpenContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_WithdrawFromContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawFromContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).WithdrawFromContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_WithdrawFromContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).WithdrawFromContainer(ctx, req.(*WithdrawFromContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_DepositToContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositToContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).DepositToContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_DepositToContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).DepositToContainer(ctx, req.(*DepositToContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_CraftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CraftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).CraftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_CraftItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).CraftItem(ctx, req.(*CraftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_SmeltItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmeltItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).SmeltItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_SmeltItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).SmeltItem(ctx, req.(*SmeltItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_Eat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).Eat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_Eat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).Eat(ctx, req.(*EatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_HarvestBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HarvestBlockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).HarvestBlock(m, &grpc.GenericServerStream[HarvestBlockRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_HarvestBlockServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_Gather_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GatherRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).Gather(m, &grpc.GenericServerStream[GatherRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_GatherServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_BuildStructure_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildStructureRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).BuildStructure(m, &grpc.GenericServerStream[BuildStructureRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_BuildStructureServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_ProcessAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).ProcessAll(m, &grpc.GenericServerStream[ProcessAllRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_ProcessAllServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_OrganizeInventory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrganizeInventoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).OrganizeInventory(m, &grpc.GenericServerStream[OrganizeInventoryRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_OrganizeInventoryServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_ClearArea_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClearAreaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).ClearArea(m, &grpc.GenericServerStream[ClearAreaRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_ClearAreaServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_Farm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FarmRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).Farm(m, &grpc.GenericServerStream[FarmRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_FarmServer = grpc.ServerStreamingServer[TaskProgress]

func _MinecraftService_SurveyArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SurveyAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).SurveyArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_SurveyArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).SurveyArea(ctx, req.(*SurveyAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_FindNearest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNearestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).FindNearest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_FindNearest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).FindNearest(ctx, req.(*FindNearestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_WhatCanICraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhatCanICraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).WhatCanICraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_WhatCanICraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).WhatCanICraft(ctx, req.(*WhatCanICraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_AssessThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).AssessThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_AssessThreat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).AssessThreat(ctx, req.(*AssessThreatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_PlanPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).PlanPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinecraftService_PlanPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).PlanPath(ctx, req.(*PlanPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinecraftService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinecraftServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, GameEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinecraftService_SubscribeEventsServer = grpc.ServerStreamingServer[GameEvent]

// MinecraftService_ServiceDesc is the grpc.ServiceDesc for MinecraftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinecraftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minecraft.MinecraftService",
	HandlerType: (*MinecraftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVitalSigns",
			Handler:    _MinecraftService_GetVitalSigns_Handler,
		},
		{
			MethodName: "GetSurroundings",
			Handler:    _MinecraftService_GetSurroundings_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _MinecraftService_GetInventory_Handler,
		},
		{
			MethodName: "TakeScreenshot",
			Handler:    _MinecraftService_TakeScreenshot_Handler,
		},
		{
			MethodName: "MoveTo",
			Handler:    _MinecraftService_MoveTo_Handler,
		},
		{
			MethodName: "LookAt",
			Handler:    _MinecraftService_LookAt_Handler,
		},
		{
			MethodName: "PlaceBlock",
			Handler:    _MinecraftService_PlaceBlock_Handler,
		},
		{
			MethodName: "DigBlock",
			Handler:    _MinecraftService_DigBlock_Handler,
		},
		{
			MethodName: "EquipItem",
			Handler:    _MinecraftService_EquipItem_Handler,
		},
		{
			MethodName: "UseItem",
			Handler:    _MinecraftService_UseItem_Handler,
		},
		{
			MethodName: "AttackEntity",
			Handler:    _MinecraftService_AttackEntity_Handler,
		},
		{
			MethodName: "Jump",
			Handler:    _MinecraftService_Jump_Handler,
		},
		{
			MethodName: "SetSneak",
			Handler:    _MinecraftService_SetSneak_Handler,
		},
		{
			MethodName: "SendChat",
			Handler:    _MinecraftService_SendChat_Handler,
		},
		{
			MethodName: "NavigateTo",
			Handler:    _MinecraftService_NavigateTo_Handler,
		},
		{
			MethodName: "InteractWithEntity",
			Handler:    _MinecraftService_InteractWithEntity_Handler,
		},
		{
			MethodName: "OpenContainer",
			Handler:    _MinecraftService_OpenContainer_Handler,
		},
		{
			MethodName: "WithdrawFromContainer",
			Handler:    _MinecraftService_WithdrawFromContainer_Handler,
		},
		{
			MethodName: "DepositToContainer",
			Handler:    _MinecraftService_DepositToContainer_Handler,
		},
		{
			MethodName: "CraftItem",
			Handler:    _MinecraftService_CraftItem_Handler,
		},
		{
			MethodName: "SmeltItem",
			Handler:    _MinecraftService_SmeltItem_Handler,
		},
		{
			MethodName: "Eat",
			Handler:    _MinecraftService_Eat_Handler,
		},
		{
			MethodName: "SurveyArea",
			Handler:    _MinecraftService_SurveyArea_Handler,
		},
		{
			MethodName: "FindNearest",
			Handler:    _MinecraftService_FindNearest_Handler,
		},
		{
			MethodName: "WhatCanICraft",
			Handler:    _MinecraftService_WhatCanICraft_Handler,
		},
		{
			MethodName: "AssessThreat",
			Handler:    _MinecraftService_AssessThreat_Handler,
		},
		{
			MethodName: "PlanPath",
			Handler:    _MinecraftService_PlanPath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HarvestBlock",
			Handler:       _MinecraftService_HarvestBlock_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Gather",
			Handler:       _MinecraftService_Gather_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildStructure",
			Handler:       _MinecraftService_BuildStructure_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProcessAll",
			Handler:       _MinecraftService_ProcessAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OrganizeInventory",
			Handler:       _MinecraftService_OrganizeInventory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClearArea",
			Handler:       _MinecraftService_ClearArea_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Farm",
			Handler:       _MinecraftService_Farm_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _MinecraftService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "minecraft.proto",
}
